# Generated by Django 3.2.16 on 2022-10-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagery',
            name='local_image',
        ),
        migrations.AlterField(
            model_name='imagery',
            name='image_details',
            field=models.CharField(default='[]', max_length=300),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='image_name',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='remote_image',
            field=models.TextField(db_column='remote_image', default='[]'),
        ),
    ]
