# Generated by Django 4.0.6 on 2022-09-29 00:17

from django.db import migrations
import ndarraydjango.fields
import numpy


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='remote_image',
            field=ndarraydjango.fields.NDArrayField(blank=True, dtype=numpy.uint16, editable=True, null=True, shape=(32, 4)),
        ),
        migrations.AlterModelTable(
            name='imagery',
            table='Imagery',
        ),
    ]
