# Generated by Django 3.2.16 on 2022-10-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20221011_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='shapefile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
