# Generated by Django 4.0.6 on 2022-09-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_alter_imagery_remote_image_alter_imagery_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagery',
            table=None,
        ),
    ]
