# Generated by Django 4.0.6 on 2022-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_imagery_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='image_details',
            field=models.CharField(default='[]', max_length=300),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='image_name',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
