# Generated by Django 3.2.16 on 2022-10-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_imagery_shapefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagery',
            old_name='shapefile',
            new_name='shapefile_path',
        ),
    ]
