# Generated by Django 3.2.16 on 2022-10-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_rename_shapefile_imagery_shapefile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
    ]
