# Generated by Django 4.0.6 on 2022-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_alter_imagery_remote_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='remote_image',
            field=models.TextField(db_column='remote_image', default='[]'),
        ),
    ]
