# Generated by Django 4.0.6 on 2022-10-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_alter_imagery_remote_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagery',
            name='local_image',
        ),
    ]
