# Generated by Django 3.2.16 on 2022-10-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_imagery_shapefile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
