# Generated by Django 3.2.16 on 2022-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_alter_imagery_shapefile_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagery',
            old_name='shapefile_path',
            new_name='shapefile_path_shp',
        ),
        migrations.AddField(
            model_name='imagery',
            name='shapefile_path_dbf',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
        migrations.AddField(
            model_name='imagery',
            name='shapefile_path_prj',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
        migrations.AddField(
            model_name='imagery',
            name='shapefile_path_sbn',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
        migrations.AddField(
            model_name='imagery',
            name='shapefile_path_sbx',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
        migrations.AddField(
            model_name='imagery',
            name='shapefile_path_shx',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
    ]
