# Generated by Django 3.2.16 on 2022-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20221017_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_dbf',
            field=models.FileField(blank=True, null=True, upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_prj',
            field=models.FileField(blank=True, null=True, upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_sbn',
            field=models.FileField(blank=True, null=True, upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_sbx',
            field=models.FileField(blank=True, null=True, upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_shp',
            field=models.FileField(blank=True, null=True, upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_shx',
            field=models.FileField(blank=True, null=True, upload_to='shapefiles'),
        ),
    ]
