# Generated by Django 3.2.16 on 2022-11-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_auto_20221114_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagery',
            name='image_details',
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='remote_image',
        ),
        migrations.AlterField(
            model_name='imagery',
            name='image_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
