# Generated by Django 3.2.16 on 2022-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_auto_20221115_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='mei',
            field=models.TextField(db_column='mei', default='mei'),
        ),
        migrations.AddField(
            model_name='imagery',
            name='normalized_difference',
            field=models.TextField(db_column='normalized_difference', default='[]'),
        ),
        migrations.AddField(
            model_name='imagery',
            name='vigs',
            field=models.TextField(db_column='vigs', default='vigs'),
        ),
    ]
