# Generated by Django 3.2.16 on 2022-11-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0017_imagery_band_stack_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='k_value',
            field=models.TextField(db_column='k_value', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='imagery',
            name='ks_value',
            field=models.TextField(db_column='ks_value', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='imagery',
            name='num_subdimensions',
            field=models.TextField(db_column='num_subdimensions', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='imagery',
            name='sample_size',
            field=models.TextField(db_column='sample_size', default='', max_length=30),
        ),
    ]
