# Generated by Django 3.2.16 on 2022-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0018_auto_20221125_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='spectral_index_color_palette',
            field=models.TextField(db_column='spectral_index_color_palette', default=''),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='k_value',
            field=models.TextField(db_column='k_value', default='3', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='ks_value',
            field=models.TextField(db_column='ks_value', default='256', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='num_subdimensions',
            field=models.TextField(db_column='num_subdimensions', default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='sample_size',
            field=models.TextField(db_column='sample_size', default='500', max_length=30),
        ),
    ]
