# Generated by Django 3.2.16 on 2022-12-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0019_auto_20221128_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='kmeans_labels',
            field=models.TextField(db_column='kmeans_labels', default=''),
        ),
        migrations.AddField(
            model_name='imagery',
            name='pqkmeans_labels',
            field=models.TextField(db_column='pqkmeans_labels', default=''),
        ),
    ]
