# Generated by Django 3.2.16 on 2022-12-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0020_auto_20221216_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectral_index_name', models.TextField(db_column='spectral_index_name', default='')),
                ('spectral_index_color_palette', models.TextField(db_column='spectral_index_color_palette', default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='spectral_index_color_palette',
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='spectral_index_name',
        ),
        migrations.AddField(
            model_name='imagery',
            name='spectral_index_name_palette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectral_index_name_palette', to='capstone.spectralindex'),
        ),
    ]
