# Generated by Django 3.2.16 on 2023-01-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0022_auto_20221221_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='bucket_name',
            field=models.TextField(db_column='bucket_name', default=''),
        ),
    ]
