# Generated by Django 3.2.16 on 2023-01-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0023_imagery_bucket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagery',
            name='bucket_name',
        ),
        migrations.AddField(
            model_name='spectralindex',
            name='bucket_name',
            field=models.TextField(db_column='bucket_name', default=''),
        ),
    ]
