# Generated by Django 3.2.16 on 2023-01-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0024_auto_20230105_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='bucket_name',
            field=models.TextField(db_column='bucket_name', default=''),
        ),
    ]
