# Generated by Django 3.2.16 on 2023-01-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0025_imagery_bucket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_dbf',
            field=models.FileField(default='/media/default_shapfiles/Lobito_1.dbf', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_prj',
            field=models.FileField(default='/media/default_shapfiles/Lobito_1.prj', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_sbn',
            field=models.FileField(default='/media/default_shapfiles/Lobito_1.sbn', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_sbx',
            field=models.FileField(default='/media/default_shapfiles/Lobito_1.sbx', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_shp',
            field=models.FileField(default='/media/default_shapfiles/Lobito_1.shp', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_shx',
            field=models.FileField(default='/media/default_shapfiles/Lobito_1.shx', upload_to='shapefiles'),
        ),
    ]
