# Generated by Django 3.2.16 on 2023-01-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0027_auto_20230105_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_dbf',
            field=models.FileField(default='C:\\Users\\arngo\\Desktop\\capstone2\\arngolo/media/default_shapfiles/dummy_shapefile.dbf', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_prj',
            field=models.FileField(default='C:\\Users\\arngo\\Desktop\\capstone2\\arngolo/media/default_shapfiles/dummy_shapefile.prj', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_sbn',
            field=models.FileField(default='C:\\Users\\arngo\\Desktop\\capstone2\\arngolo/media/default_shapfiles/dummy_shapefile.sbn', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_sbx',
            field=models.FileField(default='C:\\Users\\arngo\\Desktop\\capstone2\\arngolo/media/default_shapfiles/dummy_shapefile.sbx', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_shp',
            field=models.FileField(default='C:\\Users\\arngo\\Desktop\\capstone2\\arngolo/media/default_shapfiles/dummy_shapefile.shp', upload_to='shapefiles'),
        ),
        migrations.AlterField(
            model_name='imagery',
            name='shapefile_path_shx',
            field=models.FileField(default='C:\\Users\\arngo\\Desktop\\capstone2\\arngolo/media/default_shapfiles/dummy_shapefile.shx', upload_to='shapefiles'),
        ),
    ]
